export const CLIENTS_REQUEST_SEARCH_BEGIN = 'CLIENTS_REQUEST_SEARCH_BEGIN';
export const CLIENTS_REQUEST_SEARCH_SUCCESS = 'CLIENTS_REQUEST_SEARCH_SUCCESS';
export const CLIENTS_REQUEST_SEARCH_FAILURE = 'CLIENTS_REQUEST_SEARCH_FAILURE';
export const CLIENTS_REQUEST_SEARCH_DISMISS_ERROR = 'CLIENTS_REQUEST_SEARCH_DISMISS_ERROR';
export const CLIENTS_REQUEST_CLIENT_BY_ID_BEGIN = 'CLIENTS_REQUEST_CLIENT_BY_ID_BEGIN';
export const CLIENTS_REQUEST_CLIENT_BY_ID_SUCCESS = 'CLIENTS_REQUEST_CLIENT_BY_ID_SUCCESS';
export const CLIENTS_REQUEST_CLIENT_BY_ID_FAILURE = 'CLIENTS_REQUEST_CLIENT_BY_ID_FAILURE';
export const CLIENTS_REQUEST_CLIENT_BY_ID_DISMISS_ERROR = 'CLIENTS_REQUEST_CLIENT_BY_ID_DISMISS_ERROR';
