export const CLIENTS_REQUEST_SEARCH_BEGIN = 'CLIENTS_REQUEST_SEARCH_BEGIN';
export const CLIENTS_REQUEST_SEARCH_SUCCESS = 'CLIENTS_REQUEST_SEARCH_SUCCESS';
export const CLIENTS_REQUEST_SEARCH_FAILURE = 'CLIENTS_REQUEST_SEARCH_FAILURE';
export const CLIENTS_REQUEST_SEARCH_DISMISS_ERROR = 'CLIENTS_REQUEST_SEARCH_DISMISS_ERROR';
