export const REPORTS_REQUEST_GRANT_REPORT_BEGIN = 'REPORTS_REQUEST_GRANT_REPORT_BEGIN';
export const REPORTS_REQUEST_GRANT_REPORT_SUCCESS = 'REPORTS_REQUEST_GRANT_REPORT_SUCCESS';
export const REPORTS_REQUEST_GRANT_REPORT_FAILURE = 'REPORTS_REQUEST_GRANT_REPORT_FAILURE';
export const REPORTS_REQUEST_GRANT_REPORT_DISMISS_ERROR = 'REPORTS_REQUEST_GRANT_REPORT_DISMISS_ERROR';
export const REPORTS_REQUEST_CODESET_BEGIN = 'REPORTS_REQUEST_CODESET_BEGIN';
export const REPORTS_REQUEST_CODESET_SUCCESS = 'REPORTS_REQUEST_CODESET_SUCCESS';
export const REPORTS_REQUEST_CODESET_FAILURE = 'REPORTS_REQUEST_CODESET_FAILURE';
export const REPORTS_REQUEST_CODESET_DISMISS_ERROR = 'REPORTS_REQUEST_CODESET_DISMISS_ERROR';
