export const APP_LOGOUT_BEGIN = 'APP_LOGOUT_BEGIN';
export const APP_LOGOUT_SUCCESS = 'APP_LOGOUT_SUCCESS';
export const APP_LOGOUT_FAILURE = 'APP_LOGOUT_FAILURE';
export const APP_LOGOUT_DISMISS_ERROR = 'APP_LOGOUT_DISMISS_ERROR';
