export const GRANTS_REQUEST_SEARCH_BEGIN = 'GRANTS_REQUEST_SEARCH_BEGIN';
export const GRANTS_REQUEST_SEARCH_SUCCESS = 'GRANTS_REQUEST_SEARCH_SUCCESS';
export const GRANTS_REQUEST_SEARCH_FAILURE = 'GRANTS_REQUEST_SEARCH_FAILURE';
export const GRANTS_REQUEST_SEARCH_DISMISS_ERROR = 'GRANTS_REQUEST_SEARCH_DISMISS_ERROR';
