export const GRANTS_REQUEST_SEARCH_BEGIN = 'GRANTS_REQUEST_SEARCH_BEGIN';
export const GRANTS_REQUEST_SEARCH_SUCCESS = 'GRANTS_REQUEST_SEARCH_SUCCESS';
export const GRANTS_REQUEST_SEARCH_FAILURE = 'GRANTS_REQUEST_SEARCH_FAILURE';
export const GRANTS_REQUEST_SEARCH_DISMISS_ERROR = 'GRANTS_REQUEST_SEARCH_DISMISS_ERROR';
export const GRANTS_REQUEST_GRANT_BY_ID_BEGIN = 'GRANTS_REQUEST_GRANT_BY_ID_BEGIN';
export const GRANTS_REQUEST_GRANT_BY_ID_SUCCESS = 'GRANTS_REQUEST_GRANT_BY_ID_SUCCESS';
export const GRANTS_REQUEST_GRANT_BY_ID_FAILURE = 'GRANTS_REQUEST_GRANT_BY_ID_FAILURE';
export const GRANTS_REQUEST_GRANT_BY_ID_DISMISS_ERROR = 'GRANTS_REQUEST_GRANT_BY_ID_DISMISS_ERROR';
