export const COMMON_SHOW_ALERT_BEGIN = 'COMMON_SHOW_ALERT_BEGIN';
export const COMMON_SHOW_ALERT_SUCCESS = 'COMMON_SHOW_ALERT_SUCCESS';
export const COMMON_SHOW_ALERT_FAILURE = 'COMMON_SHOW_ALERT_FAILURE';
export const COMMON_SHOW_ALERT_DISMISS_ERROR = 'COMMON_SHOW_ALERT_DISMISS_ERROR';
